FROM golang:1.12

ARG MOSN_TAGS=v0.12.0
ARG MOSN_CODE=${MOSN_TAGS}.tar.gz
ARG MOSN_CODE_URL=https://github.com/mosn/mosn/archive/${MOSN_CODE}

WORKDIR /mosn

ADD ${MOSN_CODE_URL} .
RUN tar -xf ${MOSN_CODE} --strip 1 && rm ${MOSN_CODE}

WORKDIR /mosn/examples/codes/trace/skywalking/http

RUN go build -o http-client client.go

FROM alpine:3.10
COPY --from=builder /mosn/examples/codes/trace/skywalking/http/http-client .

ENTRYPOINT ["/http-client"]