FROM golang:1.12

ARG MOSN_TAGS=v0.12.0
ARG HTTP_SERVER_CODE=https://raw.githubusercontent.com/mosn/mosn/${MOSN_TAGS}/examples/codes/trace/skywalking/http/server.go

WORKDIR /mosn

ADD ${HTTP_SERVER_CODE} .

ENTRYPOINT ["go", "run", "server.go"]