FROM alpine:3.10

ARG MOSN_VERSION=v0.12.0

WORKDIR /mosn

ADD https://github.com/mosn/mosn/releases/download/${MOSN_VERSION}/mosn .

ADD https://raw.githubusercontent.com/mosn/mosn/${MOSN_VERSION}/examples/codes/trace/skywalking/http/config.json .

RUN chmod +x mosn

ENTRYPOINT ["/mosn/mosn", "start", "-c", "config.json"]
